In [228]:
import pandas as bamboo

**Series**: a one-dimensional, labeled array-like object capable of holding data of any type

In [229]:
data=[10.2,20.3,30.1,40.5]
series=bamboo.Series(data,index=['a','b','c','d'])
print(series)
print(series.loc['c'])                             #loc=location by label

a    10.2
b    20.3
c    30.1
d    40.5
dtype: float64
30.1

In [230]:
obj=['A','Y','U','S','H']
series=bamboo.Series(obj)
series.loc[4]='A'
print(series)

0    A
1    Y
2    U
3    S
4    A
dtype: object

In [231]:
calories={"Day 1":1800,"Day 2":2500,"Day 3":1900}
series=bamboo.Series(calories)
print(series)
series.loc["Day 1"]+=200
print(series[series>=2000])

Day 1    1800
Day 2    2500
Day 3    1900
dtype: int64
Day 1    2000
Day 2    2500
dtype: int64

**DATA FRAMES:** a two-dimensional, size-mutable data structure with labeled axes (rows and columns)

In [232]:
data={
    "Name":["Barun","Shishir","Remon"],
      "Age":["60","5","50"]
    }
df=bamboo.DataFrame(data,index=['Employee1','Employee2','Employee3'])
# print(df.loc['Employee1']) OR, using iloc property
print(df.iloc[1])

#add new column
df["Job"]=["Cook","Housekeeper","Washerman"]
print(df)

#add new row
row=bamboo.DataFrame([{"Name":"Yodin","Age":"69","Job":"Sleeper"}],
                     index=['Employee4'])
df=bamboo.concat([df,row])
print(df)

Name    Shishir
Age           5
Name: Employee2, dtype: object
              Name Age          Job
Employee1    Barun  60         Cook
Employee2  Shishir   5  Housekeeper
Employee3    Remon  50    Washerman
              Name Age          Job
Employee1    Barun  60         Cook
Employee2  Shishir   5  Housekeeper
Employee3    Remon  50    Washerman
Employee4    Yodin  69      Sleeper

**Importing:**

In [233]:
from google.colab import files
uploaded = files.upload()

Saving data.csv to data (8).csv

**READ CSV FILE**

In [234]:
df=bamboo.read_csv("data.csv",index_col="Pulse")  #leading index as Pulse
df

       Duration  Maxpulse  Calories
Pulse
110          60       130     409.1
117          60       145     479.0
103          60       135     340.0
109          45       175     282.4
117          45       148     406.0
...         ...       ...       ...
105          60       140     290.8
110          60       145     300.0
115          60       145     310.2
120          75       150     320.4
125          75       150     330.4

[169 rows x 3 columns]

In [235]:
df = bamboo.read_csv('data.csv')
print(df.to_string())             #to print all data in dataframe

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
17         45     90       112       NaN
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
27         60    103       132       NaN
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.0
37         60    100       120     300.0
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.0
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
91         45    107       137       NaN
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110     500.0
102        90     90       100     500.0
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128     124.0
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124     275.0
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141     443.0
117        60     97       122     277.4
118        60    105       125       NaN
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122     271.0
126        60     97       124     275.3
127        60    109       127     382.0
128        90     99       125     466.4
129        60    114       151     384.0
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133     335.0
133        60    106       132     327.5
134        60    103       136     339.0
135        20    136       156     189.0
136        45    117       143     317.7
137        45    115       137     318.0
138        45    113       138     308.0
139        20    141       162     222.4
140        60    108       135     390.0
141        60     97       127       NaN
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136     400.0
147        60    112       146     361.9
148        30    103       127     185.0
149        60    110       150     409.4
150        60    106       134     343.0
151        60    109       129     353.2
152        60    109       138     374.0
153        30    150       167     275.8
154        60    105       128     328.0
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

**SELECTION:**

-Selection by column

In [236]:
print(df["Calories"])

0      409.1
1      479.0
2      340.0
3      282.4
4      406.0
       ...
164    290.8
165    300.0
166    310.2
167    320.4
168    330.4
Name: Calories, Length: 169, dtype: float64

In [237]:
print(df[["Calories","Maxpulse"]])

     Calories  Maxpulse
0       409.1       130
1       479.0       145
2       340.0       135
3       282.4       175
4       406.0       148
..        ...       ...
164     290.8       140
165     300.0       145
166     310.2       145
167     320.4       150
168     330.4       150

[169 rows x 2 columns]

-Selection by Row

In [238]:
print(df.loc[0])

Duration     60.0
Pulse       110.0
Maxpulse    130.0
Calories    409.1
Name: 0, dtype: float64

In [239]:
print(df.loc[5:15:2,["Pulse","Calories"]])  #start:end:step
print(df.iloc[0:10:2,0:3]) #iloc=integer position based indexing

    Pulse  Calories
5     102     300.0
7     104     253.3
9      98     269.0
11    100     250.7
13    104     379.3
15     98     215.2
   Duration  Pulse  Maxpulse
0        60    110       130
2        60    103       135
4        45    117       148
6        60    110       136
8        30    109       133

In [240]:
SN=int(input("enter the Sn:"))
try:
  print(df.loc[SN])
except KeyError:
  print(f"{SN} not found")

enter the Sn:19
Duration     45.0
Pulse        97.0
Maxpulse    125.0
Calories    243.0
Name: 19, dtype: float64

**FILTERING:** Keeping the rows that matches the condition

In [241]:
Dur=df[df["Duration"]>= 150]
Dur

     Duration  Pulse  Maxpulse  Calories
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
69        300    108       143    1500.2
70        150     97       129    1115.0
73        150     97       127     953.2
79        270    100       131    1729.0
90        180    101       127     600.1
106       180     90       120     800.3
109       210    137       184    1860.4

**Aggregation:** used to summarize and annalyze data

Aggregate Function for whole dataframe

In [242]:
print(df.mean(numeric_only=True))

Duration     63.846154
Pulse       107.461538
Maxpulse    134.047337
Calories    375.790244
dtype: float64

In [243]:
print(df.sum(numeric_only=True))

Duration    10790.0
Pulse       18161.0
Maxpulse    22654.0
Calories    61629.6
dtype: float64

In [244]:
print(df.count())

Duration    169
Pulse       169
Maxpulse    169
Calories    164
dtype: int64

FOR single column

In [245]:
print(df["Pulse"].mean())

107.46153846153847

In [246]:
print(df["Calories"].sum())

61629.600000000006

Groupby

In [247]:
group=df.groupby("Pulse")
group["Calories"].mean()

Pulse
80      145.700000
83       50.300000
85      250.400000
90      401.227273
92      192.233333
93      317.033333
95      158.633333
97      522.383333
98      313.233333
99      369.700000
100     424.978947
101     449.550000
102     312.333333
103     291.887500
104     310.275000
105     397.840000
106     276.666667
107     419.228571
108     663.957143
109     378.122222
110     422.614286
111     371.933333
112     277.900000
113     308.000000
114     371.450000
115     311.066667
116     443.000000
117     400.900000
118     413.333333
119     336.700000
120     320.400000
121     450.700000
122     335.400000
123     482.050000
124     124.200000
125     330.400000
129     242.000000
130     300.000000
136     299.066667
137    1860.400000
141     222.400000
149     344.000000
150     201.600000
151     264.700000
152     244.200000
153     226.400000
159     319.200000
Name: Calories, dtype: float64

In [248]:
group["Maxpulse"].sum()

Pulse
80      220
83      107
85      120
90     1373
92      341
93      365
95      370
97      885
98      740
99      244
100    2388
101     251
102     769
103    1196
104     529
105     794
106     786
107    1064
108     980
109    1274
110     969
111     846
112     283
113     138
114     587
115     426
116     141
117     436
118     413
119     169
120     150
121     146
122     149
123     298
124     139
125     150
129     103
130     101
136     501
137     184
141     162
149     169
150     338
151     338
152     168
153     172
159     182
Name: Maxpulse, dtype: int64

**DATA CLEANING::** process of fixing/removing incomplete,incorrect,irrevelent data

Drop Irrevelent Column

In [249]:
df=df.drop(columns=["Pulse","Calories"])
df

     Duration  Maxpulse
0          60       130
1          60       145
2          60       135
3          45       175
4          45       148
..        ...       ...
164        60       140
165        60       145
166        60       145
167        75       150
168        75       150

[169 rows x 2 columns]

Handle Missing Data

In [250]:
df=bamboo.read_csv("data.csv")
df = df.dropna(subset=["Calories"]) #dropna=drop not available
print(df.to_string())  #118 is drop

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
5          60    102       127     300.0
6          60    110       136     374.0
7          45    104       134     253.3
8          30    109       133     195.1
9          60     98       124     269.0
10         60    103       147     329.3
11         60    100       120     250.7
12         60    106       128     345.3
13         60    104       132     379.3
14         60     98       123     275.0
15         60     98       120     215.2
16         60    100       120     300.0
18         60    103       123     323.0
19         45     97       125     243.0
20         60    108       131     364.2
21         45    100       119     282.0
22         60    130       101     300.0
23         45    105       132     246.0
24         60    102       126     334.5
25         60    100       120     250.0
26         60     92       118     241.0
28         60    100       132     280.0
29         60    102       129     380.3
30         60     92       115     243.0
31         45     90       112     180.1
32         60    101       124     299.0
33         60     93       113     223.0
34         60    107       136     361.0
35         60    114       140     415.0
36         60    102       127     300.0
37         60    100       120     300.0
38         60    100       120     300.0
39         45    104       129     266.0
40         45     90       112     180.1
41         60     98       126     286.0
42         60    100       122     329.4
43         60    111       138     400.0
44         60    111       131     397.0
45         60     99       119     273.0
46         60    109       153     387.6
47         45    111       136     300.0
48         45    108       129     298.0
49         60    111       139     397.6
50         60    107       136     380.2
51         80    123       146     643.1
52         60    106       130     263.0
53         60    118       151     486.0
54         30    136       175     238.0
55         60    121       146     450.7
56         60    118       121     413.0
57         45    115       144     305.0
58         20    153       172     226.4
59         45    123       152     321.0
60        210    108       160    1376.0
61        160    110       137    1034.4
62        160    109       135     853.0
63         45    118       141     341.0
64         20    110       130     131.4
65        180     90       130     800.4
66        150    105       135     873.4
67        150    107       130     816.0
68         20    106       136     110.4
69        300    108       143    1500.2
70        150     97       129    1115.0
71         60    109       153     387.6
72         90    100       127     700.0
73        150     97       127     953.2
74         45    114       146     304.0
75         90     98       125     563.2
76         45    105       134     251.0
77         45    110       141     300.0
78        120    100       130     500.4
79        270    100       131    1729.0
80         30    159       182     319.2
81         45    149       169     344.0
82         30    103       139     151.1
83        120    100       130     500.0
84         45    100       120     225.3
85         30    151       170     300.0
86         45    102       136     234.0
87        120    100       157    1000.1
88         45    129       103     242.0
89         20     83       107      50.3
90        180    101       127     600.1
92         30     90       107     105.3
93         15     80       100      50.5
94         20    150       171     127.4
95         20    151       168     229.4
96         30     95       128     128.2
97         25    152       168     244.2
98         30    109       131     188.2
99         90     93       124     604.1
100        20     95       112      77.7
101        90     90       110     500.0
102        90     90       100     500.0
103        90     90       100     500.4
104        30     92       108      92.7
105        30     93       128     124.0
106       180     90       120     800.3
107        30     90       120      86.2
108        90     90       120     500.3
109       210    137       184    1860.4
110        60    102       124     325.2
111        45    107       124     275.0
112        15    124       139     124.2
113        45    100       120     225.3
114        60    108       131     367.6
115        60    108       151     351.7
116        60    116       141     443.0
117        60     97       122     277.4
119        60    103       124     332.7
120        30    112       137     193.9
121        45    100       120     100.7
122        60    119       169     336.7
123        60    107       127     344.9
124        60    111       151     368.5
125        60     98       122     271.0
126        60     97       124     275.3
127        60    109       127     382.0
128        90     99       125     466.4
129        60    114       151     384.0
130        60    104       134     342.5
131        60    107       138     357.5
132        60    103       133     335.0
133        60    106       132     327.5
134        60    103       136     339.0
135        20    136       156     189.0
136        45    117       143     317.7
137        45    115       137     318.0
138        45    113       138     308.0
139        20    141       162     222.4
140        60    108       135     390.0
142        45    100       120     250.4
143        45    122       149     335.4
144        60    136       170     470.2
145        45    106       126     270.8
146        60    107       136     400.0
147        60    112       146     361.9
148        30    103       127     185.0
149        60    110       150     409.4
150        60    106       134     343.0
151        60    109       129     353.2
152        60    109       138     374.0
153        30    150       167     275.8
154        60    105       128     328.0
155        60    111       151     368.5
156        60     97       131     270.4
157        60    100       120     270.4
158        60    114       150     382.8
159        30     80       120     240.9
160        30     85       120     250.4
161        45     90       130     260.4
162        45     95       130     270.0
163        45    100       140     280.9
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

In [251]:
df=bamboo.read_csv("data.csv")
df=df.fillna({"Calories":"NONONO"})
print(df.to_string())

     Duration  Pulse  Maxpulse Calories
0          60    110       130    409.1
1          60    117       145    479.0
2          60    103       135    340.0
3          45    109       175    282.4
4          45    117       148    406.0
5          60    102       127    300.0
6          60    110       136    374.0
7          45    104       134    253.3
8          30    109       133    195.1
9          60     98       124    269.0
10         60    103       147    329.3
11         60    100       120    250.7
12         60    106       128    345.3
13         60    104       132    379.3
14         60     98       123    275.0
15         60     98       120    215.2
16         60    100       120    300.0
17         45     90       112   NONONO
18         60    103       123    323.0
19         45     97       125    243.0
20         60    108       131    364.2
21         45    100       119    282.0
22         60    130       101    300.0
23         45    105       132    246.0
24         60    102       126    334.5
25         60    100       120    250.0
26         60     92       118    241.0
27         60    103       132   NONONO
28         60    100       132    280.0
29         60    102       129    380.3
30         60     92       115    243.0
31         45     90       112    180.1
32         60    101       124    299.0
33         60     93       113    223.0
34         60    107       136    361.0
35         60    114       140    415.0
36         60    102       127    300.0
37         60    100       120    300.0
38         60    100       120    300.0
39         45    104       129    266.0
40         45     90       112    180.1
41         60     98       126    286.0
42         60    100       122    329.4
43         60    111       138    400.0
44         60    111       131    397.0
45         60     99       119    273.0
46         60    109       153    387.6
47         45    111       136    300.0
48         45    108       129    298.0
49         60    111       139    397.6
50         60    107       136    380.2
51         80    123       146    643.1
52         60    106       130    263.0
53         60    118       151    486.0
54         30    136       175    238.0
55         60    121       146    450.7
56         60    118       121    413.0
57         45    115       144    305.0
58         20    153       172    226.4
59         45    123       152    321.0
60        210    108       160   1376.0
61        160    110       137   1034.4
62        160    109       135    853.0
63         45    118       141    341.0
64         20    110       130    131.4
65        180     90       130    800.4
66        150    105       135    873.4
67        150    107       130    816.0
68         20    106       136    110.4
69        300    108       143   1500.2
70        150     97       129   1115.0
71         60    109       153    387.6
72         90    100       127    700.0
73        150     97       127    953.2
74         45    114       146    304.0
75         90     98       125    563.2
76         45    105       134    251.0
77         45    110       141    300.0
78        120    100       130    500.4
79        270    100       131   1729.0
80         30    159       182    319.2
81         45    149       169    344.0
82         30    103       139    151.1
83        120    100       130    500.0
84         45    100       120    225.3
85         30    151       170    300.0
86         45    102       136    234.0
87        120    100       157   1000.1
88         45    129       103    242.0
89         20     83       107     50.3
90        180    101       127    600.1
91         45    107       137   NONONO
92         30     90       107    105.3
93         15     80       100     50.5
94         20    150       171    127.4
95         20    151       168    229.4
96         30     95       128    128.2
97         25    152       168    244.2
98         30    109       131    188.2
99         90     93       124    604.1
100        20     95       112     77.7
101        90     90       110    500.0
102        90     90       100    500.0
103        90     90       100    500.4
104        30     92       108     92.7
105        30     93       128    124.0
106       180     90       120    800.3
107        30     90       120     86.2
108        90     90       120    500.3
109       210    137       184   1860.4
110        60    102       124    325.2
111        45    107       124    275.0
112        15    124       139    124.2
113        45    100       120    225.3
114        60    108       131    367.6
115        60    108       151    351.7
116        60    116       141    443.0
117        60     97       122    277.4
118        60    105       125   NONONO
119        60    103       124    332.7
120        30    112       137    193.9
121        45    100       120    100.7
122        60    119       169    336.7
123        60    107       127    344.9
124        60    111       151    368.5
125        60     98       122    271.0
126        60     97       124    275.3
127        60    109       127    382.0
128        90     99       125    466.4
129        60    114       151    384.0
130        60    104       134    342.5
131        60    107       138    357.5
132        60    103       133    335.0
133        60    106       132    327.5
134        60    103       136    339.0
135        20    136       156    189.0
136        45    117       143    317.7
137        45    115       137    318.0
138        45    113       138    308.0
139        20    141       162    222.4
140        60    108       135    390.0
141        60     97       127   NONONO
142        45    100       120    250.4
143        45    122       149    335.4
144        60    136       170    470.2
145        45    106       126    270.8
146        60    107       136    400.0
147        60    112       146    361.9
148        30    103       127    185.0
149        60    110       150    409.4
150        60    106       134    343.0
151        60    109       129    353.2
152        60    109       138    374.0
153        30    150       167    275.8
154        60    105       128    328.0
155        60    111       151    368.5
156        60     97       131    270.4
157        60    100       120    270.4
158        60    114       150    382.8
159        30     80       120    240.9
160        30     85       120    250.4
161        45     90       130    260.4
162        45     95       130    270.0
163        45    100       140    280.9
164        60    105       140    290.8
165        60    110       145    300.0
166        60    115       145    310.2
167        75    120       150    320.4
168        75    125       150    330.4

Fix inconsistance value

In [252]:
df["Duration"]=df["Duration"].replace({60:69})
df

     Duration  Pulse  Maxpulse Calories
0          69    110       130    409.1
1          69    117       145    479.0
2          69    103       135    340.0
3          45    109       175    282.4
4          45    117       148    406.0
..        ...    ...       ...      ...
164        69    105       140    290.8
165        69    110       145    300.0
166        69    115       145    310.2
167        75    120       150    320.4
168        75    125       150    330.4

[169 rows x 4 columns]

**Standardize text:**
df["Name"]=df["Name"].str.lower()

**FIX DATA TYPES:**

In [253]:
df["Calories"]=df["Calories"].astype(bool)
print(df.to_string())

     Duration  Pulse  Maxpulse  Calories
0          69    110       130      True
1          69    117       145      True
2          69    103       135      True
3          45    109       175      True
4          45    117       148      True
5          69    102       127      True
6          69    110       136      True
7          45    104       134      True
8          30    109       133      True
9          69     98       124      True
10         69    103       147      True
11         69    100       120      True
12         69    106       128      True
13         69    104       132      True
14         69     98       123      True
15         69     98       120      True
16         69    100       120      True
17         45     90       112      True
18         69    103       123      True
19         45     97       125      True
20         69    108       131      True
21         45    100       119      True
22         69    130       101      True
23         45    105       132      True
24         69    102       126      True
25         69    100       120      True
26         69     92       118      True
27         69    103       132      True
28         69    100       132      True
29         69    102       129      True
30         69     92       115      True
31         45     90       112      True
32         69    101       124      True
33         69     93       113      True
34         69    107       136      True
35         69    114       140      True
36         69    102       127      True
37         69    100       120      True
38         69    100       120      True
39         45    104       129      True
40         45     90       112      True
41         69     98       126      True
42         69    100       122      True
43         69    111       138      True
44         69    111       131      True
45         69     99       119      True
46         69    109       153      True
47         45    111       136      True
48         45    108       129      True
49         69    111       139      True
50         69    107       136      True
51         80    123       146      True
52         69    106       130      True
53         69    118       151      True
54         30    136       175      True
55         69    121       146      True
56         69    118       121      True
57         45    115       144      True
58         20    153       172      True
59         45    123       152      True
60        210    108       160      True
61        160    110       137      True
62        160    109       135      True
63         45    118       141      True
64         20    110       130      True
65        180     90       130      True
66        150    105       135      True
67        150    107       130      True
68         20    106       136      True
69        300    108       143      True
70        150     97       129      True
71         69    109       153      True
72         90    100       127      True
73        150     97       127      True
74         45    114       146      True
75         90     98       125      True
76         45    105       134      True
77         45    110       141      True
78        120    100       130      True
79        270    100       131      True
80         30    159       182      True
81         45    149       169      True
82         30    103       139      True
83        120    100       130      True
84         45    100       120      True
85         30    151       170      True
86         45    102       136      True
87        120    100       157      True
88         45    129       103      True
89         20     83       107      True
90        180    101       127      True
91         45    107       137      True
92         30     90       107      True
93         15     80       100      True
94         20    150       171      True
95         20    151       168      True
96         30     95       128      True
97         25    152       168      True
98         30    109       131      True
99         90     93       124      True
100        20     95       112      True
101        90     90       110      True
102        90     90       100      True
103        90     90       100      True
104        30     92       108      True
105        30     93       128      True
106       180     90       120      True
107        30     90       120      True
108        90     90       120      True
109       210    137       184      True
110        69    102       124      True
111        45    107       124      True
112        15    124       139      True
113        45    100       120      True
114        69    108       131      True
115        69    108       151      True
116        69    116       141      True
117        69     97       122      True
118        69    105       125      True
119        69    103       124      True
120        30    112       137      True
121        45    100       120      True
122        69    119       169      True
123        69    107       127      True
124        69    111       151      True
125        69     98       122      True
126        69     97       124      True
127        69    109       127      True
128        90     99       125      True
129        69    114       151      True
130        69    104       134      True
131        69    107       138      True
132        69    103       133      True
133        69    106       132      True
134        69    103       136      True
135        20    136       156      True
136        45    117       143      True
137        45    115       137      True
138        45    113       138      True
139        20    141       162      True
140        69    108       135      True
141        69     97       127      True
142        45    100       120      True
143        45    122       149      True
144        69    136       170      True
145        45    106       126      True
146        69    107       136      True
147        69    112       146      True
148        30    103       127      True
149        69    110       150      True
150        69    106       134      True
151        69    109       129      True
152        69    109       138      True
153        30    150       167      True
154        69    105       128      True
155        69    111       151      True
156        69     97       131      True
157        69    100       120      True
158        69    114       150      True
159        30     80       120      True
160        30     85       120      True
161        45     90       130      True
162        45     95       130      True
163        45    100       140      True
164        69    105       140      True
165        69    110       145      True
166        69    115       145      True
167        75    120       150      True
168        75    125       150      True

In [254]:
df=df.drop_duplicates()
df

     Duration  Pulse  Maxpulse  Calories
0          69    110       130      True
1          69    117       145      True
2          69    103       135      True
3          45    109       175      True
4          45    117       148      True
..        ...    ...       ...       ...
164        69    105       140      True
165        69    110       145      True
166        69    115       145      True
167        75    120       150      True
168        75    125       150      True

[151 rows x 4 columns]